import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout dédié à app/live/* (page publique acheteur, sans sélecteur de
// thème) : toujours en light mode, indépendamment du thème dark/light choisi
// côté vendeur dans le dashboard. Pas de ThemeProvider ici — c'est
// app/(themed)/layout.tsx (autre root layout, via route group) qui le monte
// pour le reste de l'app. Deux root layouts distincts, chacun avec ses
// propres <html>/<body>, cf. Next.js route groups.
export default function BuyerRootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
